# Generated by go2rpm 1.8.2
%bcond_without check

# https://github.com/google/go-tpm-tools
%global goipath         github.com/google/go-tpm-tools
Version:                0.3.9
%global tag             launcher/v0.3.9
%global distprefix      %{nil}

%gometa -f

%global common_description %{expand:
Go packages built on go-tpm providing a high-level API for using TPMs.}

%global golicenses      LICENSE simulator_ms-tpm-20-ref_LICENSE
%global godocs          README.md simulator_README.md \\\
                        simulator_ms-tpm-20-ref_README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go packages built on go-tpm providing a high-level API for using TPMs

License:        Apache-2.0 AND BSD-2-Clause
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:  openssl1.1-devel

%description %{common_description}

%gopkg

%prep
%goprep

find launcher -name '*.go' | xargs sed -i \
    's|"google.golang.org/api|"github.com/josephlr/google-api-go-client|'

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/gotpm ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
mv simulator/README.md simulator_README.md
mv simulator/ms-tpm-20-ref/README.md simulator_ms-tpm-20-ref_README.md
mv simulator/ms-tpm-20-ref/LICENSE simulator_ms-tpm-20-ref_LICENSE

%if %{with check}
%check
# Disable tests that require network acccess
for test in TestNetworkFetchIssuingCertificate; do
    awk -i inplace \
        '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' \
        $(grep -rl $test)
done
%gocheck
%endif

%files
%license LICENSE simulator_ms-tpm-20-ref_LICENSE
%doc README.md simulator_README.md
%doc simulator_ms-tpm-20-ref_README.md
%{_bindir}/gotpm

%gopkgfiles

%changelog
%autochangelog
