# Generated by go2rpm 1.8.2
%bcond_without check
%bcond_without bootstrap

# https://github.com/google/go-tpm-tools
%global goipath         github.com/google/go-tpm-tools

Version:                0.3.9
%global tag             v0.3.9

%gometa -f

%global goipathsex      github.com/google/go-tpm-tools/launcher
%global goipaths0       github.com/google/go-attestation
%global goipathsex0     github.com/google/go-attestation/attest

%global common_description %{expand:
Go packages built on go-tpm providing a high-level API for using TPMs.}

%global golicenses      LICENSE simulator/ms-tpm-20-ref/LICENSE
%global godocs          CONTRIBUTING.md README.md simulator/README.md\\\
                        simulator/ms-tpm-20-ref/CONTRIBUTING.md simulator/ms-\\\
                        tpm-20-ref/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go packages built on go-tpm providing a high-level API for using TPMs

License:        BSD-2-Clause AND Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

BuildRequires: openssl-devel
BuildRequires: golang(github.com/google/go-attestation/attest)

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in launcher; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE simulator/ms-tpm-20-ref/LICENSE
%doc CONTRIBUTING.md README.md simulator/README.md
%doc simulator/ms-tpm-20-ref/CONTRIBUTING.md simulator/ms-tpm-20-ref/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
